### ISSUE TITLE
Lunar Nuget -> “Sequence contains no elements”

### ISSUE THREAD

**Issue by CohortMinseok** [Dewera/Lunar#13]
When I go to the Nuget manager I only see Lunar-RPatch v1.1.0...Is this the latest version?

I'm getting a previous issue: “Sequence contains no elements”
My project is built with QT GUI.

**Comment by Dewera** [comment]
This library isn't hosted on the official Nuget feed, rather on the GitHub package registry.  Try again using the latest version.

If you still get the issue it is likely because the current version is having issues finding dependencies and will be fixed properly in the next update (which will happen soon after .Net 5 releases)
