### ISSUE TITLE
Injected DLL doesn't show up in the PEB module list

### ISSUE THREAD

**Issue by dhiru1602** [Dewera/Lunar#7]
I am using Lunar to inject a DLL into a process which works fine. However, I wanted to debug the DLL and I am unable to do so because the PEB module list doesn't have the DLL listed. This prevents Visual Studio from triggering a breakpoint in the DLL code after attaching to the injected EXE because the DLL is not present in the module list. I understand that this is probably due to manual mapping, however I have a legitimate usecase where-in I don't want to do stealth DLL injection. Is there a possibility you could add the functionality to update the PEB module list by adding an extra parameter to MapLibrary()?

**Comment by Dewera** [comment]
This is a difficult task to get right due to the various internal structures that need references added to outside of the standard linked lists you're referring to in the PEB.

This is planned for a future update and will be integrated directly into the mapping process by default, with the option to opt-out via a set of flags, similar to how LoadLibrary does it `dwFlags` argument (i.e. LOAD_LIBRARY_AS_DATAFILE.)
